# Google Cloud Build configuration for DATect deployment
# Builds the container image with pre-computed cache
# Cost-optimized: scales to zero when idle (~$0/month for low-traffic demos)

steps:
  # Step 1: Build the production container image with pre-computed cache
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-production-image'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.production'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/datect:latest'
      - '.'
    timeout: '900s'  # 15 minutes for build (no cache computation)

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/datect:latest'

  # Step 3: Deploy to Cloud Run (cost-optimized for demo/low-traffic)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloud-run'
    args:
      - 'run'
      - 'deploy'
      - 'datect-api'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/datect:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'           # Scale to zero when idle — no charges when not in use
      - '--max-instances'
      - '3'           # Reduced from 5; plenty for demo traffic
      - '--concurrency'
      - '20'          # Reduced from 200; realistic for a demo app
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'CACHE_DIR=/app/cache,NODE_ENV=production,PYTHONPATH=/app'

# Configure build resources
options:
  logging: CLOUD_LOGGING_ONLY

# Default values - can be overridden
substitutions:
  _REGION: us-west1

# Build timeout
timeout: '1200s'  # 20 minutes total

# Tags for organization
tags:
  - 'datect'
  - 'production'
  - 'cached'